name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: all ways

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
    name: Download a Build Artifact
     + uses: actions/download-artifact@v2.0.10
      with:
     Artifact name
    name:  Custom Rail
     Destination path
    path: optional
